export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const FETCH_POKEMON_PAGE_WISE = 'FETCH_POKEMON_PAGE_WISE';
export const FETCH_ALL_POKEMONS = 'FETCH_ALL_POKEMON';
export const FETCH_POKEMON_BY_SEARCH = 'FETCH_POKEMON_BY_SEARCH';
export const FETCH_CURRENT_POKEMON = 'FETCH_CURRENT_POKEMON';
export const SET_FILTERED_POKEMON = 'SET_FILTERED_POKEMON';